### ISSUE TITLE
Can't exit zen mode without closing and reopening

### ISSUE THREAD

**Issue by codebroker40** [aki237/zen-mode#1]
I just installed this package and could enter the mode just fine using a key binding or just M-x zen-mode.  However, when I run M-x zen-mode again or use the bind to exit it I get an error saying " wrong type argument: listp, window-size-change-functions."

**Comment by aki237** [comment]
Sure, Let me look into it.

**Comment by mmagnus** [comment]
Yeah, the same problem over here.

**Comment by tim-hilt** [comment]
I have the same problem. Doing what it should otherwise. Much simpler than something like sublimity-mode!

**Comment by aki237** [comment]
Sorry for the late response. I've pushed a commit to master. Can y'all test against that?

**Comment by tim-hilt** [comment]
Wow, that was fast! Works for me now. Thanks.

**Comment by aki237** [comment]
Closing the issue.
